CREATE TABLE IF NOT EXISTS `voters` (
    `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `email` varchar(255) NOT NULL,
    `password` varchar(255) NOT NULL,
    `cpf` varchar(14) NOT NULL,
    `birth_date` date NOT NULL,
    `phone` varchar(20) DEFAULT NULL,
    `vote_weight` decimal(3,2) NOT NULL DEFAULT 1.00,
    `is_active` tinyint(1) NOT NULL DEFAULT 1,
    `is_verified` tinyint(1) NOT NULL DEFAULT 0,
    `verification_token` varchar(255) DEFAULT NULL,
    `last_login_at` timestamp NULL DEFAULT NULL,
    `last_login_ip` varchar(45) DEFAULT NULL,
    `email_verified_at` timestamp NULL DEFAULT NULL,
    `remember_token` varchar(100) DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `voters_email_unique` (`email`),
    UNIQUE KEY `voters_cpf_unique` (`cpf`),
    KEY `idx_voters_email` (`email`),
    KEY `idx_voters_cpf` (`cpf`),
    KEY `idx_voters_active` (`is_active`),
    KEY `idx_voters_verified` (`is_verified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;