CREATE TABLE IF NOT EXISTS `elections` (
    `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL,
    `description` text DEFAULT NULL,
    `election_type` enum('federal','state','municipal','internal') NOT NULL DEFAULT 'internal',
    `status` enum('draft','scheduled','active','completed','cancelled') NOT NULL DEFAULT 'draft',
    `start_date` datetime NOT NULL,
    `end_date` datetime NOT NULL,
    `timezone` varchar(50) NOT NULL DEFAULT 'UTC',
    `allow_blank_votes` tinyint(1) NOT NULL DEFAULT 1,
    `allow_null_votes` tinyint(1) NOT NULL DEFAULT 1,
    `require_justification` tinyint(1) NOT NULL DEFAULT 0,
    `max_votes_per_voter` int(11) NOT NULL DEFAULT 1,
    `voting_method` enum('single','multiple','ranked') NOT NULL DEFAULT 'single',
    `results_visibility` enum('private','public','after_end') NOT NULL DEFAULT 'after_end',
    `created_by` bigint(20) UNSIGNED NOT NULL,
    `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_elections_status` (`status`),
    KEY `idx_elections_dates` (`start_date`, `end_date`),
    KEY `idx_elections_type` (`election_type`),
    KEY `fk_elections_created_by` (`created_by`),
    KEY `fk_elections_updated_by` (`updated_by`),
    CONSTRAINT `fk_elections_created_by` FOREIGN KEY (`created_by`) REFERENCES `admins` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_elections_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `admins` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
