CREATE TABLE IF NOT EXISTS `votes` (
    `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `election_id` bigint(20) UNSIGNED NOT NULL,
    `position_id` bigint(20) UNSIGNED NOT NULL,
    `voter_id` bigint(20) UNSIGNED NOT NULL,
    `candidate_hash` varchar(255) NOT NULL,
    `vote_hash` varchar(255) NOT NULL,
    `vote_weight` decimal(3,2) NOT NULL DEFAULT 1.00,
    `vote_type` enum('candidate','blank','null') NOT NULL DEFAULT 'candidate',
    `ip_address` varchar(45) NOT NULL,
    `user_agent` text DEFAULT NULL,
    `session_id` varchar(255) DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `unique_voter_position_election` (`voter_id`, `position_id`, `election_id`),
    KEY `idx_votes_election` (`election_id`),
    KEY `idx_votes_position` (`position_id`),
    KEY `idx_votes_voter` (`voter_id`),
    KEY `idx_votes_hash` (`vote_hash`),
    KEY `idx_votes_candidate_hash` (`candidate_hash`),
    KEY `idx_votes_type` (`vote_type`),
    KEY `idx_votes_created` (`created_at`),
    CONSTRAINT `fk_votes_election` FOREIGN KEY (`election_id`) REFERENCES `elections` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_votes_position` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_votes_voter` FOREIGN KEY (`voter_id`) REFERENCES `voters` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;