CREATE TABLE IF NOT EXISTS `audit_logs` (
    `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` bigint(20) UNSIGNED DEFAULT NULL,
    `user_type` enum('admin','voter','system') NOT NULL DEFAULT 'system',
    `action` varchar(100) NOT NULL,
    `resource` varchar(100) NOT NULL,
    `resource_id` bigint(20) UNSIGNED DEFAULT NULL,
    `route` varchar(255) DEFAULT NULL,
    `method` varchar(10) DEFAULT NULL,
    `ip_address` varchar(45) NOT NULL,
    `user_agent` text DEFAULT NULL,
    `request_data` json DEFAULT NULL,
    `response_data` json DEFAULT NULL,
    `status_code` int(11) DEFAULT NULL,
    `execution_time` decimal(8,3) DEFAULT NULL,
    `memory_usage` bigint(20) DEFAULT NULL,
    `session_id` varchar(255) DEFAULT NULL,
    `correlation_id` varchar(255) DEFAULT NULL,
    `level` enum('emergency','alert','critical','error','warning','notice','info','debug') NOT NULL DEFAULT 'info',
    `message` text DEFAULT NULL,
    `context` json DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_audit_logs_user` (`user_id`, `user_type`),
    KEY `idx_audit_logs_action` (`action`),
    KEY `idx_audit_logs_resource` (`resource`, `resource_id`),
    KEY `idx_audit_logs_ip` (`ip_address`),
    KEY `idx_audit_logs_created` (`created_at`),
    KEY `idx_audit_logs_level` (`level`),
    KEY `idx_audit_logs_session` (`session_id`),
    KEY `idx_audit_logs_correlation` (`correlation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;